<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BigRig.Api.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BigRig.Domain\BigRig.Domain.csproj" />
    <ProjectReference Include="..\BigRig.Contracts\BigRig.Contracts.csproj" />
    <ProjectReference Include="..\BigRig.Data\BigRig.Data.csproj" />
  </ItemGroup>

</Project>
